-- ============================================================
-- USANG — JANGAN JALANKAN FAIL INI
-- ============================================================
-- Fail ni dulu buka polisi "public delete orders" (sesiapa boleh padam
-- pesanan). Selepas migration-keselamatan.sql, admin padam pesanan melalui
-- Edge Function store-api — polisi awam ni TIDAK diperlukan lagi dan akan
-- membuka semula lubang keselamatan kalau dijalankan.
--
-- Kandungan asal (disimpan sebagai rujukan sahaja):
--   drop policy if exists "public delete orders" on orders;
--   create policy "public delete orders" on orders for delete using (true);
